### ISSUE TITLE
Django outdated

### ISSUE THREAD

**Issue by nhendy** [PurdueCAM2Project/CAM2WebUI#307]
Django has undergone a an update recently and deprecated several features being used in CAM2 website. 

One of which is the login view for users.

Please refer to [this](https://docs.djangoproject.com/en/dev/releases/2.1/#features-deprecated-in-2-1)

This feature was actually removed in 2.0 and we're using 1.11.1 which is way behind. 

You can see the deprecation timeline [here](https://docs.djangoproject.com/en/dev/internals/deprecation/)

**Comment by matthew-ardi** [comment]
we had a discussion on this earlier this year. 
see the timeline on [supported version docs](https://www.djangoproject.com/download/).
we decided to stick with 1.11.1 because of its Long term support. 

However, I would suggest go to 1.11.16, that's the latest release but keep it under version 1.11 until version 2.2 is released

**Comment by SionHu** [comment]
We will be discussing and finalize the django version to be used at today's meeting.
